services:
  tailscale-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
        - ./:/workspace
        - ~/.vscode-server/bin:/root/.vscode-server/bin
        - tailscale-dev-vsc:/root/.vscode-server/extensions
    stdin_open: true
    tty: true
    init: true

volumes:
  tailscale-dev-vsc: